Fix target blank links
circleci/circleci.com-shared pull request #5
Opened 2021-08-17 19:31 UTC by bardan-circleci

just updated line 14 of `js/analytics-recursive-tracking.js` to be `var targetElement = e.currentTarget;` because the right now, if you click on a footer social icon, the `e.target` is the icon itself and not the `href` tag. Switching it to the `e.currentTarget` will give us the element that triggered the event listener - which is what we want as that's the element with `[data-analytics]` prop.

**Note: if we merge the other PRs to master, the rest of the changes (other than in `js/analytics-recursive-tracking.js` file) - that are part of this pr - will prob stop showing up as part of this pr.

2021-08-17 20:04 UTC, j2em6h requested changes
I am still seeing the social links opening in the same window. 

http://static-preview.circleci.com/fix-footer-social-links/

2021-08-17 20:04 UTC, j2em6h commented on js/analytics-recursive-tracking.js
> +      var targetElement = e.currentTarget;
The `targetElement` variable is only used on line 15, there are other uses of `e.target`s in the rest of this function that probably can be replaced with `targetElement`

2021-08-17 20:10 UTC, bardan-circleci commented on js/analytics-recursive-tracking.js
> +      var targetElement = e.currentTarget;
oh true true, will replace them with `targetElement`!

And my bad, I jumped the gun a too early here. The code update doesn't seem to have fixed it. I swear I thought it fixed on my local setup yesterday when I tried the `e.currentTarget` so I started the pr. However, there's something else that's blocking the link from opening in a new window.

I'm still investigating it on my local setup. I'll ping again once I have gotten it working on local and on preview site. Thanks!

2021-08-18 19:26 UTC, bardan-circleci commented on js/analytics-recursive-tracking.js
> +      if (!blankTarget && isLinkTag) {
[comment]

so basically the problem was that in the list of elements that we attach the click listener to, footer element is one of them (grabbed by the `data-analytics` document query) - along with social links. When the user clicks a social link, a click event is simultaneously triggered on the `<a>` tag as well as the `<footer>` tag as the link is inside the footer.

Since we're only checking to see if the element clicked has a blank target or not (footer doesn't), the code prevents the event default (aka opening in new window - in this case). I'm adding a check here to make sure we're only preventing default is the element that triggered the event is an `<a>` tag - which will filter out footer or divs.

2021-08-18 19:27 UTC, bardan-circleci commented on js/analytics-recursive-tracking.js
> +      var targetElement = e.target; // the element that's actually clicked
[comment]

Upon further thinking, `el` here is same as using `e.currentTarget` so I'm going to use that instead and keep the `targetElement = e.target` as that is still being tracked below on line 25 for analytics purposes.

2021-08-18 19:29 UTC, bardan-circleci commented on js/analytics-recursive-tracking.js
> +      if (link && !blankTarget && isLinkTag) {
[comment]

We also don't want to change the window's location unless its a link tag that's being clicked. Currently click event on the footer triggers it - which was whats making the link open in the same window.

2021-08-18 22:28 UTC, j2em6h requested changes
This is working for the `target="_blank"` issue, but the event tracking is not happening (and was not happening before either, due to the `target` vs `currentTarget` you mentioned originally). I made [new ticket](https://circleci.atlassian.net/browse/WEB-390) that describes that specific issue. 

I ended up making a different change in the new-footer PR that addressed the social icons specifically, but the root cause still exists.

2021-08-18 22:28 UTC, j2em6h commented on js/analytics-recursive-tracking.js
> +      if (!blankTarget && isLinkTag) {
The `isLinkTag` check is not needed here, since "preventDefault" on something like a `span` or an `image` will have no effect, as there is no default behaviour on click.

2021-08-18 22:28 UTC, j2em6h commented on js/analytics-recursive-tracking.js
> +      if (link && !blankTarget && isLinkTag) {
The `isLinkTag` isn't needed here, since there is already a check for `link`

2021-08-18 22:28 UTC, j2em6h commented on js/analytics-recursive-tracking.js
> +      var targetElement = e.target; // the element that's actually clicked
If `e.target` is not an `a` tag, then there won't be the `data-analytics-child` on it either. We would want the `e.currentTarget` to be used for line 25 also.

2021-08-18 22:28 UTC, j2em6h commented on js/analytics-recursive-tracking.js
> +              JSON.parse(targetElement.getAttribute('data-analytics-child'))
The `data-analytics-child` attribute will not exist on a non-`a` element.

2021-08-18 22:57 UTC, bardan-circleci commented on js/analytics-recursive-tracking.js
> +      if (!blankTarget && isLinkTag) {
so I added it based on https://stackoverflow.com/questions/5620730/event-preventdefault-and-multiple-events 

It seems that `event.preventDefault` prevents the browser's events from happening so while there's no event prevention tied to the clicking of the footer/div/span/etc., the click events fire off together for `a` tag and the `footer` tag simultaneously like I mentioned above and the footer's click event leads to `event.preventDefault` which also stops the `a` tag's opening of new window. 

If you put a debugger on `line 21` and click a social icon, you'll see that it catches the `a` tag's event and then right after, it'll catch the click event for the footer, which will step into line 22 and prevents the browser from opening the window. If I leave out the `isLinkTag` check, then the link doesn't open in new window.

2021-08-18 23:15 UTC, bardan-circleci commented on js/analytics-recursive-tracking.js
> +      if (link && !blankTarget && isLinkTag) {
hmm this is confusing to explain so let me try with timeline lol

- grabs list of elements prop matching `data-analytics` prop (it grabs `footer` and social `a` tags)
- attach click event listeners to all of them so now we have footer and a tags with click event listeners
- user clicks a social `a` tag, event listener fires off for both the `a` tag and the `footer` tag since both have listeners attached and `a` tag is inside footer
- we go through this event listener code for `a` tag, everything is fine
- we go through even listener code for `footer` tag, the recursive function finds the `a` tag's href as it's the "last" 
- `link` variable becomes true and `!blankTarget` also becomes true since it has no `target=_blank`
- window location changes, taking the user to a new url vs opening a window

so the current code works perfectly but the anomaly here is the click event on the footer firing and it seems to mess the conditions up. If i didn't add a condition to only prevent default and change window location for link tags, then footer click event fires them and what get what we have right now

2021-08-19 01:51 UTC, bardan-circleci commented on js/analytics-recursive-tracking.js
> +      var targetElement = e.target; // the element that's actually clicked
I did bit more digging here:

The event listeners are attached to elements with `data-analytics` and in some cases, those elements also happen to have `data-analytics-parent` which are usually div/footer elements. So when we click a svg/span inside the `a` tag that has the `data-analytics-child`, `e.currentTarget` is actually the footer/div element in that scenario (bcoz that's the element event listener is attached to) and not the `a` tag which is what we want.

So, I see two ways to solve this problem:

1. Using CSS, we set all the elements inside the `a` tag to have `pointer-events: none` - which will stop span/svg/img/etc to be registered as the `e.target` and it will bubble up to the `a` tag - which will give us the `data-analytics-child` attribute and we can track the event. I've tested this and it works. 
2. Or in our JS code, we can check if the `e.target` is an `a` tag or not, if it is, we can just grab the `data-analytics-child` attribute from it. If it's not an `a` tag, then it's prob svg/span and we can use `e.target.parentNode` to grab its parent node which is `a` tag and then grab the `data-analytics-child` attribute from the parent node.

CSS vs JS
- If we go CSS route, it's might be a bit tedious to set the child elements inside `a` tag in the footer to have `pointer-events: none;` although we could try one liner like `.footer a > * { pointer-events: none; }` and apply broadly.
- If we go the JS route, we have to be careful to not wrap the span/svg inside `a` tag with another div tag or something like that - which will set the parent node to be div and not the `a` tag.

I don't know if I'm explaining all these well or not. I would be happy to jump on a call and discuss this - might be easier to show and explain. Let me know if you prefer that.

2021-08-19 21:13 UTC, closed without merging